spring:
  application:
    name: devops-panel
  datasource:
    url: ${DB_URL:jdbc:h2:mem:devops_panel;DB_CLOSE_DELAY=-1}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

# JWT
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration-ms: 86400000

server:
  port: ${PORT:8081}

logging:
  level:
    com.devops: INFO
    org.springframework.security: INFO
